from building import *
Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
if not src:
    
    LIBS    = ['arm_cortexM7lfdp_math']
    
    LIBPATH = [cwd]
else:
    LIBS    = []
    LIBPATH = []

group   = DefineGroup('dsplib', src, depend = [''], CPPPATH = CPPPATH, LIBS = LIBS, LIBPATH=LIBPATH)

Return('group')
