Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'aq_src')
src	= Glob('*.c')
	
	
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('AQ_src', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
